#!/bin/sh /etc/rc.common

START=20
STOP=90

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
	#wiware added
	/bin/sh /wiware/bin/initnetwork.sh
	##

	stop

	[ -e /proc/sys/kernel/core_pattern ] && {
		ulimit -c unlimited
		echo '/tmp/%e.%p.%s.%t.core' > /proc/sys/kernel/core_pattern
	}
	
	service_start /sbin/netifd

	setup_switch() { return 0; }

	include /lib/network
	setup_switch

	sleep 3

	/sbin/wifi down
	/sbin/wifi up
}

restart() {
	ifdown -a
	sleep 1
	start
}

shutdown() {
	ifdown -a
	stop
}

stop() {
	service_stop /sbin/netifd
}

reload() {
	ubus call network reload
	/sbin/wifi down
	if [ ! "$(uci get wireless.@wifi-iface[0].disabled 2>/dev/null)" = "1" ]; then
                /sbin/wifi up
        fi
	#wiware added
	killall udhcpc
	nginx -s reload
}
